name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
    - run: yarn

    - name: Run linting
    - run: yarn lint

    - name: Run Automated test
    - run: yarn test
      env:
        CI: true
